// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvdi0bTCQxI6BjM1hKj3MR8AuPx6Oj5A',
    appId: '1:819195743543:web:beb6b88373160c1c0c9eb2',
    messagingSenderId: '819195743543',
    projectId: 'gestalt-facial-db',
    authDomain: 'gestalt-facial-db.firebaseapp.com',
    storageBucket: 'gestalt-facial-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PybIRm9wUtuZwxvU0ehA_rArDK_XtgA',
    appId: '1:819195743543:android:9f0cf844d1e7abbf0c9eb2',
    messagingSenderId: '819195743543',
    projectId: 'gestalt-facial-db',
    storageBucket: 'gestalt-facial-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBopXuKmSMZK-IjEFJt_J9JViDQzjT9CHk',
    appId: '1:819195743543:ios:c198e9684eb9da480c9eb2',
    messagingSenderId: '819195743543',
    projectId: 'gestalt-facial-db',
    storageBucket: 'gestalt-facial-db.firebasestorage.app',
    iosClientId: '819195743543-qeumd7jghdktmerk4l90j6jt8facvsoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaltDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBopXuKmSMZK-IjEFJt_J9JViDQzjT9CHk',
    appId: '1:819195743543:ios:c198e9684eb9da480c9eb2',
    messagingSenderId: '819195743543',
    projectId: 'gestalt-facial-db',
    storageBucket: 'gestalt-facial-db.firebasestorage.app',
    iosClientId: '819195743543-qeumd7jghdktmerk4l90j6jt8facvsoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaltDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwvdi0bTCQxI6BjM1hKj3MR8AuPx6Oj5A',
    appId: '1:819195743543:web:7de94e39182ffe4b0c9eb2',
    messagingSenderId: '819195743543',
    projectId: 'gestalt-facial-db',
    authDomain: 'gestalt-facial-db.firebaseapp.com',
    storageBucket: 'gestalt-facial-db.firebasestorage.app',
  );

}